language: python
matrix:
  include:
    - python: 3.7
      env: TOXENV=flake8
    - python: 3.7
      env: TOXENV=prospector

    - python: 2.7
      env: TOXENV=unit-py27
    - python: 3.4
      env: TOXENV=unit-py34
    - python: 3.5.0
      env: TOXENV=unit-py35
    - python: 3.5.1
      env: TOXENV=unit-py35
    - python: 3.5.2
      env: TOXENV=unit-py35
    - python: 3.5.3
      env: TOXENV=unit-py35
    - python: 3.5-dev
      env: TOXENV=unit-py35
    - python: 3.6.0
      env: TOXENV=unit-py36
    - python: 3.6-dev
      env: TOXENV=unit-py36
    - python: 3.7.0
      env: TOXENV=unit-py37
      dist: xenial
    - python: 3.7-dev
      env: TOXENV=unit-py37
      dist: xenial

install:
  - set -e
  - set -u
  - pip install tox

script:
  - set -e
  - set -u
  - export TOX_SKIP_MISSING_INTERPRETERS="False"
  - tox