dist: xenial
language: python
matrix:
  include:
    - python: 3.7
      env: TOXENV=flake8
    - python: 3.7
      env: TOXENV=prospector

    - python: 2.7
      env: TOXENV=flake8
    - python: 3.4
      env: TOXENV=flake8
    - python: 3.5.0
      env: TOXENV=flake8
    - python: 3.5.1
      env: TOXENV=flake8
    - python: 3.5.2
      env: TOXENV=flake8
    - python: 3.5.3
      env: TOXENV=flake8
    - python: 3.5-dev
      env: TOXENV=flake8
    - python: 3.6.0
      env: TOXENV=flake8
    - python: 3.6-dev
      env: TOXENV=flake8
    - python: 3.7.0
      env: TOXENV=flake8
    - python: 3.7-dev
      env: TOXENV=flake8
python:
  - "2.7"
  - "3.4"
  - "3.5.0"
  - "3.5.1"
  - "3.5.2"
  - "3.5.3"
  - "3.5-dev"
  - "3.6.0"
  - "3.6-dev"
  - "3.7-dev"

install:
  - ./.travis/install

script:
  - ./.travis/run tox