language: python
python:
    - "2.7"
    - "3.4"
    - "3.5.0"
    - "3.5.1"
    - "3.5.2"
    - "3.5.3"
    - "3.5-dev"
    - "3.6.0"
    - "3.6-dev"
    - "3.7.0"
    - "3.7-dev"

install: "make"

script:
    - make test